# Propiedades de Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Versiones de Minecraft / Fabric para 1.20.1
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.11

# Dependencias del mod (Fabric API incluye el módulo de networking v1)
fabric_version=0.92.2+1.20.1

# Info del mod
mod_version=1.0.0
maven_group=net.bsmp.plushies
archives_base_name=bsmp-plushies
